---
fullname: VLSM
shortname: vlsm
organization: runtimeverification
community: false
dune: false
action: true
coqdoc: true

synopsis: >-
  Coq formalization of validating labelled state transition
  and message production systems

description: |-
  A validating labelled state transition and message production system
  (VLSM) abstractly models a distributed system with faults. This project
  contains a formalization of VLSMs and their theory in the Coq proof assistant.

publications:
- pub_doi: 10.48550/arXiv.2202.12662
  pub_url: https://arxiv.org/abs/2202.12662
  pub_title: 'Validating Labelled State Transition and Message Production Systems: A Theory for Modelling Faulty Distributed Systems'

authors:
- name: Mihai Calancea
- name: Denisa Diaconescu
- name: Wojciech Kołowski
- name: Elaine Li
- name: Brandon Moore
- name: Karl Palmskog
- name: Lucas Peña
- name: Grigore Roșu
- name: Traian Șerbănuță
- name: Dafina Trufas
- name: Jan Tušil
- name: Vlad Zamfir

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: BSD 3-Clause "New" or "Revised" License
  identifier: BSD-3-Clause
  file: LICENSE.md

supported_coq_versions:
  text: 8.15 and later
  opam: '{>= "8.15"}'

dependencies:
- opam:
    name: coq-stdpp
    version: '{>= "1.7.0"}'
  description: |-
    [Coq-std++](https://gitlab.mpi-sws.org/iris/stdpp/) 1.7.0 or later
- opam:
    name: coq-itauto
  description: |-
    [Itauto](https://gitlab.inria.fr/fbesson/itauto)
- opam:
    name: coq-equations
  description: |-
    [Coq-Equations](https://github.com/mattam82/Coq-Equations)

tested_coq_opam_versions:
- version: '8.16-ocaml-4.14-flambda'
- version: '8.15-ocaml-4.14-flambda'

namespace: VLSM

keywords:
- name: consensus
- name: fault tolerance
- name: distributed algorithms

categories:
- name: Computer Science/Concurrent Systems and Protocols/Theory of concurrent systems

build: |-
  ## Working with the project online

  The simplest way of working with this project without needing to install anything is by doing so online:

  [![Open in Papillon](https://papillon.unbounded.network/github-badge.svg)](https://papillon.unbounded.network/projects/github/runtimeverification/vlsm/master)

  ## Building instructions

  We recommend using [opam](https://opam.ocaml.org) to install project dependencies.
  Besides the basic building instructions below, we also provide a more detailed
  [building guide](BUILDING.md), with special recommendations for Windows users.

  To install the project dependencies via opam, do:

  ```shell
  opam repo add coq-released https://coq.inria.fr/opam/released
  opam install coq.8.16.1 coq-stdpp.1.8.0 coq-itauto coq-equations
  ```

  To build the project when you have all dependencies installed, do:

  ```shell
  git clone https://github.com/runtimeverification/vlsm.git
  cd vlsm
  make   # or make -j <number-of-cores-on-your-machine>
  ```

documentation: |-
  ## Coq file organization

  - `theories/VLSM/Lib`: Various extensions to the Coq standard library and Coq-std++.
  - `theories/VLSM/Core`: Core VLSM definitions and theory.

  ## Documentation

  - [latest coqdoc presentation of the Coq files](https://runtimeverification.github.io/vlsm-docs/latest/coqdoc/toc.html)
  - [latest Alectryon presentation the Coq files](https://runtimeverification.github.io/vlsm-docs/latest/alectryon/toc.html)
---
